### ISSUE TITLE
tan(pi/2) == whole?

### ISSUE THREAD

**Issue by xhebox** [mauriciopoppe/interval-arithmetic#16] opened 2018-02-16 06:56 UTC
```
 n = trigonometric.tan(new Interval(Math.PI / 2, Math.PI / 2))
assert(n.lo === Number.NEGATIVE_INFINITY)
assert(n.hi === Number.POSITIVE_INFINITY)

n = trigonometric.tan(new Interval(0, Math.PI / 2))
assert(n.lo === Number.NEGATIVE_INFINITY)
assert(n.hi === Number.POSITIVE_INFINITY)
```
From the left side, let x -> pi/2, we got +infinity, and -infinity from the right side. No numbers are in [+inifinity, -infinity]. But in your case, we got a 'whole' interval, how could it be?

The second example, we should got [0, +infinity]. For [pi/2,0], we should get [-infinity, 0]. Let me know if i am wrong :).

**Comment by mauriciopoppe** [comment] 2018-02-16 20:06
This issue happens because of the rounding operations that are carried over the whole process, for the first example it happens on this line

https://github.com/mauriciopoppe/interval-arithmetic/blob/eb6ee7bf111d21e7f52fcd6f15e503f84e0740d8/lib/operations/trigonometric.js#L175

Inside fmod the `sub` operation creates an interval that *bounds all the possible values that may have been lost due to the rounding ops*, therefore instead of representing the interval `[Math.PI/2, Math.PI/2]` it creates the interval `[Math.PI - Δ, Math.PI + Δ]` and if you apply the tan operator to the bounds the result is something like `[3530114321217157.5, -6218431163823738
]` which may be considered as a whole interval

interval-arithmetic guarantees that all the possible values that are lost using regular operations on single precision floating point numbers are kept using intervals however it might be possible that in some cases the interval created has more values than what's needed (the case that you've found is actually the worst i.e. an interval is created that represents all the points when it should represent no points at all)

**Comment by mauriciopoppe** [comment] 2018-03-28 06:48
I'm going to close this issue, feel free to reopen it if you want to continue with the discussion

**Closed by mauriciopoppe** 2018-03-28 06:48 UTC

**Comment by donhatch** [comment] 2026-04-15 23:52
(I don't have permission to reopen, but yes I'd like to continue with the discussion :-) )

I think I understand the explanation, but perhaps the behavior can be improved, by refraining from calling fmod when the argument is already in the desired range, as it is in this case?

Or, it could be addressed at a lower level, inside fmod: that is, if both x.lo and x.hi (of the first argument x) are already in the desired range, then fmod could just return x, without any expansion.

OTOH, if I'm thinking about all this correctly, this entire issue report is somewhat ill-founded, since `new Interval(Math.PI / 2, Math.PI / 2)` isn't a very useful object, and likely does not represent what was intended.  It represents a zero-width interval containing the single real number `Math.PI / 2`, which is an exactly-representable number slightly less than the mathematical value of pi/2.
So if the implementation of `tan` and/or `fmod` were improved as suggested above, then`trigonometric.tan(new Interval(Math.PI / 2, Math.PI / 2))` would return a tighter technically correct answer something like `[1.6331239353195368e+16, 1.633123935319537e+16]`.

A possible more useful/meaningful calculation (perhaps what was intended?) would be `tan(Interval.constants.PI_HALF)` , where `Interval.constants.PI_HALF` is the smallest interval with machine-representable endpoints that contains pi/2.  In that case the only correct answer is in fact [-infinity, infinity] since it must include both negative and positive numbers with unbounded magnitudes.
